spring:
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/hard-nut
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create

#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/{DB_NAME}
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: 1234
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
